import Head from 'next/head'
import { ConferencesRegistrationForm } from '@/views/ConferencesRegistrationForm';
import styles from './index.module.css';
import { prisma } from '@/prisma';
import { Report } from '@prisma/client';


interface Props {
  reports: Report[]
}

export default function Home({ reports }: Props) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>Регистрация на доклад</h1>
        <ConferencesRegistrationForm reports={reports} />
      </main>
    </>
  )
}

export async function getStaticProps() {
  const reports = await prisma.report.findMany();
  return {
    props: {
      reports
    }
  };
}
